coverage:
  range: 80..100
  round: down
  precision: 2
  status:
    project:
      default: false
    patch:
      default: false

# Tests files aren't important for coverage
ignore:
  - "tests"
  - "bench"
  - "fuzz"
